# Pre-commit configuration for PgPostalCodeSync project
repos:
  - repo: local
    hooks:
      - id: dotnet-build
        name: Build C# project
        entry: powershell -Command "Set-Location src/PgPostalCodeSync; dotnet build --verbosity quiet"
        language: system
        pass_filenames: false
        always_run: true

      - id: dotnet-format
        name: Format C# code
        entry: powershell -Command "Set-Location src/PgPostalCodeSync; dotnet format . --verbosity quiet"
        language: system
        files: '\.cs$'
        pass_filenames: false

      - id: dotnet-test
        name: Run C# tests
        entry: powershell -Command "Set-Location src/PgPostalCodeSync; if (Get-ChildItem -Name '*.Tests.csproj', '*Test*.csproj') { dotnet test --verbosity quiet } else { Write-Host 'No test projects found' }"
        language: system
        pass_filenames: false
        always_run: true

  # Standard hooks for general file maintenance
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
