-- Project Name : postal_code_sync
-- Date/Time    : 2025/08/28 22:32:42
-- Author       : ted
-- RDBMS Type   : PostgreSQL
-- Application  : A5:SQL Mk-2

/*
  << ���ӁI�I >>
  BackupToTempTable, RestoreFromTempTable�^�����߂��t������Ă��܂��B
  ����ɂ��Adrop table, create table ����f�[�^���c��܂��B
  ���̋@�\�͈ꎞ�I�� $$TableName �̂悤�Ȉꎞ�e�[�u�����쐬���܂��B
  ���̋@�\�� A5:SQL Mk-2�ł̂ݗL���ł��邱�Ƃɒ��ӂ��Ă��������B
*/

-- ext.ingestion_files
-- * BackupToTempTable
DROP TABLE if exists ext.ingestion_files CASCADE;

-- * RestoreFromTempTable
CREATE TABLE ext.ingestion_files (
  file_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
  , run_id BIGINT DEFAULT 0 NOT NULL
  , source_uri TEXT DEFAULT '' NOT NULL
  , file_name TEXT DEFAULT '' NOT NULL
  , size_bytes BIGINT DEFAULT 0 NOT NULL
  , hash_sha256 character(64) DEFAULT '' NOT NULL
  , CONSTRAINT ingestion_files_PKC PRIMARY KEY (file_id)
) ;

-- ext.ingestion_runs
-- * BackupToTempTable
DROP TABLE if exists ext.ingestion_runs CASCADE;

-- * RestoreFromTempTable
CREATE TABLE ext.ingestion_runs (
  run_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
  , source_system TEXT DEFAULT '' NOT NULL
  , version_date date
  , mode TEXT DEFAULT '' NOT NULL
  , started_at timestamp DEFAULT CURRENT_TIMESTAMP
  , finished_at timestamp
  , status TEXT DEFAULT '' NOT NULL
  , landed_rows BIGINT DEFAULT 0 NOT NULL
  , notes TEXT DEFAULT '' NOT NULL
  , errors JSONB DEFAULT '{}' NOT NULL
  , CONSTRAINT ingestion_runs_PKC PRIMARY KEY (run_id)
) ;

-- ext.postal_codes
-- * BackupToTempTable
DROP TABLE if exists ext.postal_codes CASCADE;

-- * RestoreFromTempTable
CREATE TABLE ext.postal_codes (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
  , postal_code character(7) DEFAULT '' NOT NULL
  , prefecture_katakana TEXT DEFAULT '' NOT NULL
  , city_katakana TEXT DEFAULT '' NOT NULL
  , town_katakana TEXT DEFAULT '' NOT NULL
  , prefecture TEXT DEFAULT '' NOT NULL
  , city TEXT DEFAULT '' NOT NULL
  , town TEXT DEFAULT '' NOT NULL
  , run_id BIGINT
  , CONSTRAINT postal_codes_PKC PRIMARY KEY (id)
) ;

-- ext.postal_codes_landed
-- * BackupToTempTable
DROP TABLE if exists ext.postal_codes_landed CASCADE;

-- * RestoreFromTempTable
CREATE TABLE ext.postal_codes_landed (
  local_government_code TEXT NOT NULL
  , old_zip_code5 TEXT DEFAULT '' NOT NULL
  , zip_code7 TEXT DEFAULT '' NOT NULL
  , prefecture_katakana TEXT DEFAULT '' NOT NULL
  , city_katakana TEXT DEFAULT '' NOT NULL
  , town_katakana TEXT DEFAULT '' NOT NULL
  , prefecture TEXT DEFAULT '' NOT NULL
  , city TEXT DEFAULT '' NOT NULL
  , town TEXT DEFAULT '' NOT NULL
  , is_multi_zip BOOLEAN DEFAULT FALSE NOT NULL
  , is_koaza BOOLEAN DEFAULT FALSE NOT NULL
  , is_chome BOOLEAN DEFAULT FALSE NOT NULL
  , is_multi_town BOOLEAN DEFAULT FALSE NOT NULL
  , update_status TEXT DEFAULT '' NOT NULL
  , update_reason TEXT DEFAULT '' NOT NULL
) ;

COMMENT ON TABLE ext.ingestion_files IS 'ext.ingestion_files';
COMMENT ON COLUMN ext.ingestion_files.file_id IS '�捞�t�@�C��ID';
COMMENT ON COLUMN ext.ingestion_files.run_id IS '�捞���sID';
COMMENT ON COLUMN ext.ingestion_files.source_uri IS '�擾��URI';
COMMENT ON COLUMN ext.ingestion_files.file_name IS '�t�@�C����';
COMMENT ON COLUMN ext.ingestion_files.size_bytes IS '�T�C�Y(�o�C�g)';
COMMENT ON COLUMN ext.ingestion_files.hash_sha256 IS 'SHA-256�n�b�V��';

COMMENT ON TABLE ext.ingestion_runs IS 'ext.ingestion_runs';
COMMENT ON COLUMN ext.ingestion_runs.run_id IS '�捞���sID';
COMMENT ON COLUMN ext.ingestion_runs.source_system IS '�捞���V�X�e��';
COMMENT ON COLUMN ext.ingestion_runs.version_date IS '�f�[�^�œ�';
COMMENT ON COLUMN ext.ingestion_runs.mode IS '�捞���[�h';
COMMENT ON COLUMN ext.ingestion_runs.started_at IS '�J�n����';
COMMENT ON COLUMN ext.ingestion_runs.finished_at IS '�I������';
COMMENT ON COLUMN ext.ingestion_runs.status IS '�X�e�[�^�X';
COMMENT ON COLUMN ext.ingestion_runs.landed_rows IS '�捞����';
COMMENT ON COLUMN ext.ingestion_runs.notes IS '���l';
COMMENT ON COLUMN ext.ingestion_runs.errors IS '�G���[�ڍ�';

COMMENT ON TABLE ext.postal_codes IS 'ext.postal_codes';
COMMENT ON COLUMN ext.postal_codes.id IS 'id';
COMMENT ON COLUMN ext.postal_codes.postal_code IS 'postal_code';
COMMENT ON COLUMN ext.postal_codes.prefecture_katakana IS 'prefecture_katakana';
COMMENT ON COLUMN ext.postal_codes.city_katakana IS 'city_katakana';
COMMENT ON COLUMN ext.postal_codes.town_katakana IS 'town_katakana';
COMMENT ON COLUMN ext.postal_codes.prefecture IS 'prefecture';
COMMENT ON COLUMN ext.postal_codes.city IS 'city';
COMMENT ON COLUMN ext.postal_codes.town IS 'town';
COMMENT ON COLUMN ext.postal_codes.run_id IS 'run_id';

COMMENT ON TABLE ext.postal_codes_landed IS 'ext.postal_codes_landed:���{�X�ւ̗X�֔ԍ�CSV(UTF-8)����荞�ނ��߂̈ꎞ�e�[�u���ł��B
�f�[�^���s�v�Ȃ珈����� TRUNCATE �����B
�捞�p�e�[�u�����������ꍇ�� etl �X�L�[�}�ւ̈ڍs���������܂��B';
COMMENT ON COLUMN ext.postal_codes_landed.local_government_code IS '�S���n�������c�̃R�[�h:JIS X0401�AX0402';
COMMENT ON COLUMN ext.postal_codes_landed.old_zip_code5 IS '���X�֔ԍ�(5��)';
COMMENT ON COLUMN ext.postal_codes_landed.zip_code7 IS '�X�֔ԍ�(7��)';
COMMENT ON COLUMN ext.postal_codes_landed.prefecture_katakana IS '�s���{����(�J�i)';
COMMENT ON COLUMN ext.postal_codes_landed.city_katakana IS '�s�撬����(�J�i)';
COMMENT ON COLUMN ext.postal_codes_landed.town_katakana IS '���於(�J�i)';
COMMENT ON COLUMN ext.postal_codes_landed.prefecture IS '�s���{����';
COMMENT ON COLUMN ext.postal_codes_landed.city IS '�s�撬����';
COMMENT ON COLUMN ext.postal_codes_landed.town IS '���於';
COMMENT ON COLUMN ext.postal_codes_landed.is_multi_zip IS '�����X�֔ԍ��t���O:�꒬�悪��ȏ�̗X�֔ԍ��ŕ\�����ꍇ�̕\���i"1": �Y���A"0": �Y�������j';
COMMENT ON COLUMN ext.postal_codes_landed.is_koaza IS '�����Ԓn�t���O:�������ɔԒn���N�Ԃ���Ă��钬��̕\���i"1": �Y���A"0": �Y�������j';
COMMENT ON COLUMN ext.postal_codes_landed.is_chome IS '���ڃt���O:���ڂ�L���钬��̏ꍇ�̕\���i"1": �Y���A"0": �Y�������j';
COMMENT ON COLUMN ext.postal_codes_landed.is_multi_town IS '��������t���O:��̗X�֔ԍ��œ�ȏ�̒����\���ꍇ�̕\���i"1": �Y���A"0": �Y�������j';
COMMENT ON COLUMN ext.postal_codes_landed.update_status IS '�X�V�t���O:�X�V�̕\���i"0": �ύX�Ȃ��A"1": �ύX����A"2": �p�~�j';
COMMENT ON COLUMN ext.postal_codes_landed.update_reason IS '�X�V���R:�ύX���R�i"0": �ύX�Ȃ��A"1": �s�����{�s�A"2": �Z���\���̎��{�A"3": ��搮���A"4": �X�֋撲�����A"5": �����A"6": �p�~�j';
